[tool.poetry]
name = "csak"
version = "1.0.0"
description = ""
authors = ["Gagan Malvi <malvi@aospa.co>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
